App\Entity\Company:
    properties:
        name:
            -   NotBlank: ~
            -   Type: string
        nip:
            -   NotBlank: ~
            -   Type: string
            -   Length:
                    min: 10
                    max: 10
            -   Regex:
                    pattern: '/^[0-9]+$/i'
                    htmlPattern: '[0-9]+'
        address:
            -   NotBlank: ~
            -   Type: string
        city:
            -   NotBlank: ~
            -   Type: string
        postalCode:
            -   NotBlank: ~
            -   Type: string
            -   Length:
                    max: 30    

App\Entity\Employee:
    properties:
        firstName:
            -   NotBlank: ~
            -   Type: string
            -   Length:
                    max: 30
        lastName:
            -   NotBlank: ~
            -   Type: string
            -   Length:
                    max: 40
        email:
            -   NotBlank: ~
            -   Type: string
            -   Email:
                    message: The email "{{ value }}" is not a valid email.    
        phoneNumber:
            -   Type: string
            -   Length:
                    max: 20
            
        
